name: Build chrome extension

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build chrome extension
    runs-on: ubuntu-latest    
    
    steps:      
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Run tests and produce reports
      run: npm run test:ci
    
    - name: Publish test results
      uses: IgnusG/jest-report-action@v2.3.3
      if: always()  
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }} 

    - name: Publish code coverage results
      uses: romeovs/lcov-reporter-action@v0.2.19
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: ./coverage/lcov.info

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build
    
    - name: Zip contents
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r extension.zip build

    - name: Publish to Chrome store
      uses: Klemensas/chrome-extension-upload-action@v1.3
      with:
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        file-name: './extension.zip'
        app-id: ${{ secrets.CHROME_APP_ID }}
        publish: true
